#====================================================================
#       Macro & Assembler flags
#====================================================================

STADDR = 802000
RMACFLAGS = -fb -g -i$(JAGSDK)/jaguar/include
RLNFLAGS = -z -v -e -g -l -rd -a $(STADDR) x 4000

all:	testlzss.cof

#====================================================================
#       Assembles
#====================================================================

delzjag.o:	../JAG.SRC/delzjag.s
	rmac $(RMACFLAGS) -o $@ $<

testlzss.o:	testlzss.s
	rmac $(RMACFLAGS) -o $@ $<

#====================================================================
#       Executables
#====================================================================

OBJS = testlzss.o delzjag.o
 
testlzss.cof: $(OBJS) makefile
	rln $(RLNFLAGS) -o testlzss.cof -c testlzss_lnk

#====================================================================
#       Clean
#====================================================================

clean:
	rm $(OBJS) testlzss.cof
